version: '3.6'

services:
  web:
    build: ./src
    image: storyshare_web
    tty: true
    stdin_open: true
    restart: always
    command: >
      sh -c "python manage.py migrate
      && crond
      && gunicorn storyshare.wsgi:application -t 3600 --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./src/:/var/www/storyshare/
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    command: nginx -g 'daemon off;'
    depends_on:
      - web