"""
Django settings for storyshare project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!t8e43j2$&0lw&zs!$6-vu_b5!g_fvu3u54=%rf%5yl!@$mm^w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'story',
    'background_task',
    'rest_framework',
    'video_encoding'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'storyshare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'storyshare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

VIDEO_ENCODING_FORMATS = {
        'FFmpeg': [
            {
                'name': 'webm_sd',
                'extension': 'webm',
                'params': [
                    '-b:v',
                    '1000k',
                    '-maxrate',
                    '1000k',
                    '-bufsize',
                    '2000k',
                    '-codec:v',
                    'libvpx',
                    '-r',
                    '30',
                    '-vf',
                    'scale=-1:480',
                    '-qmin',
                    '10',
                    '-qmax',
                    '42',
                    '-codec:a',
                    'libvorbis',
                    '-b:a',
                    '128k',
                    '-f',
                    'webm',
                ],
            },
            {
                'name': 'webm_hd',
                'extension': 'webm',
                'params': [
                    '-codec:v',
                    'libvpx',
                    '-b:v',
                    '3000k',
                    '-maxrate',
                    '3000k',
                    '-bufsize',
                    '6000k',
                    '-vf',
                    'scale=-1:480',
                    '-qmin',
                    '11',
                    '-qmax',
                    '51',
                    '-acodec',
                    'libvorbis',
                    '-b:a',
                    '128k',
                    '-f',
                    'webm',
                ],
            },
            {
                'name': 'mp4_sd',
                'extension': 'mp4',
                'params': [
                    '-codec:v',
                    'libx264',
                    '-crf',
                    '20',
                    '-preset',
                    'medium',
                    '-b:v',
                    '1000k',
                    '-maxrate',
                    '1000k',
                    '-bufsize',
                    '2000k',
                    '-vf',
                    'scale=-1:480',  # http://superuser.com/a/776254
                    '-codec:a',
                    'aac',
                    '-b:a',
                    '128k',
                    '-strict',
                    '-2',
                ],
            },
            {
                'name': 'mp4_hd',
                'extension': 'mp4',
                'params': [
                    '-codec:v',
                    'libx264',
                    '-crf',
                    '20',
                    '-preset',
                    'medium',
                    '-b:v',
                    '3000k',
                    '-maxrate',
                    '3000k',
                    '-bufsize',
                    '6000k',
                    '-vf',
                    'scale=-1:480',
                    '-codec:a',
                    'aac',
                    '-b:a',
                    '128k',
                    '-strict',
                    '-2',
                ],
            },
        ]
    }


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, "static_cdn")

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")