# Generated by Django 3.0.5 on 2021-03-23 13:01

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=story.models.Story.upload_image_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='story',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
