# Generated by Django 3.0.5 on 2021-03-23 14:32

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210323_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='height_field_r',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image_resized',
            field=models.ImageField(blank=True, height_field='height_field_r', null=True, upload_to=story.models.Story.upload_image_location, width_field='width_field_r'),
        ),
        migrations.AddField(
            model_name='story',
            name='width_field_r',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
