# Generated by Django 3.0.5 on 2021-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20210323_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='preprocessing_done',
            field=models.BooleanField(default=False),
        ),
    ]
