# Generated by Django 3.0.5 on 2021-03-24 11:05

from django.db import migrations, models
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20210324_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=video_encoding.fields.VideoField(blank=True, null=True, upload_to=''),
        ),
    ]
